/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package geogebra.kernel.parser;

public interface ParserConstants {

  int EOF = 0;
  int EOL = 5;
  int ASSIGNMENT = 6;
  int CARTESIAN_SPECIAL_SEPERATOR = 7;
  int NOT = 8;
  int OR = 9;
  int AND = 10;
  int EQUAL_BOOLEAN = 11;
  int NOT_EQUAL = 12;
  int LESS = 13;
  int GREATER = 14;
  int LESS_EQUAL = 15;
  int GREATER_EQUAL = 16;
  int PARALLEL = 17;
  int PERPENDICULAR = 18;
  int EQUAL = 19;
  int PLUS = 20;
  int MINUS = 21;
  int MULTIPLY = 22;
  int VECTORPRODUCT = 23;
  int DIVIDE = 24;
  int POWER = 25;
  int FACTORIAL = 26;
  int UNDEFINED = 27;
  int POWER0 = 28;
  int POWER1 = 29;
  int SQUARED = 30;
  int CUBED = 31;
  int POWER4 = 32;
  int POWER5 = 33;
  int POWER6 = 34;
  int POWER7 = 35;
  int POWER8 = 36;
  int POWER9 = 37;
  int PI = 38;
  int E = 39;
  int DEGREE = 40;
  int INFINITY = 41;
  int RAD = 42;
  int DERIVATIVE = 43;
  int TRUE = 44;
  int FALSE = 45;
  int VARX = 46;
  int VARY = 47;
  int PARAMETRICVAR = 48;
  int FLOAT = 49;
  int EFLOAT = 50;
  int INTEGER = 51;
  int DIGIT = 52;
  int ANY_LABEL = 53;
  int SPREADSHEET_LABEL = 54;
  int LABEL = 55;
  int INDEX = 56;
  int LETTER = 57;
  int X_FUNC = 58;
  int Y_FUNC = 59;
  int Z_FUNC = 60;
  int COS_FUNC = 61;
  int SIN_FUNC = 62;
  int TAN_FUNC = 63;
  int ACOS_FUNC = 64;
  int ASIN_FUNC = 65;
  int ATAN_FUNC = 66;
  int COSH_FUNC = 67;
  int SINH_FUNC = 68;
  int TANH_FUNC = 69;
  int ACOSH_FUNC = 70;
  int ASINH_FUNC = 71;
  int ATANH_FUNC = 72;
  int EXP_FUNC = 73;
  int LOG_FUNC = 74;
  int LD_FUNC = 75;
  int LG_FUNC = 76;
  int SQRT_FUNC = 77;
  int CBRT_FUNC = 78;
  int ABS_FUNC = 79;
  int SGN_FUNC = 80;
  int FLOOR_FUNC = 81;
  int CEIL_FUNC = 82;
  int ROUND_FUNC = 83;
  int GAMMA_FUNC = 84;
  int RANDOM_FUNC = 85;
  int FUNCTION_LABEL = 86;
  int TEXT = 87;
  int CHAR = 88;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\":=\"",
    "\"|\"",
    "\"\\u00ac\"",
    "<OR>",
    "<AND>",
    "<EQUAL_BOOLEAN>",
    "<NOT_EQUAL>",
    "\"<\"",
    "\">\"",
    "<LESS_EQUAL>",
    "<GREATER_EQUAL>",
    "\"\\u2225\"",
    "\"\\u22a5\"",
    "\"=\"",
    "\"+\"",
    "<MINUS>",
    "<MULTIPLY>",
    "\"\\u2297\"",
    "\"/\"",
    "\"^\"",
    "\"!\"",
    "<UNDEFINED>",
    "\"\\u2070\"",
    "\"\\u00b9\"",
    "\"\\u00b2\"",
    "\"\\u00b3\"",
    "\"\\u2074\"",
    "\"\\u2075\"",
    "\"\\u2076\"",
    "\"\\u2077\"",
    "\"\\u2078\"",
    "\"\\u2079\"",
    "<PI>",
    "\"\\u212f\"",
    "\"\\u00b0\"",
    "\"\\u221e\"",
    "\"rad\"",
    "\"\\\'\"",
    "<TRUE>",
    "<FALSE>",
    "\"x\"",
    "\"y\"",
    "\"X\"",
    "<FLOAT>",
    "<EFLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<ANY_LABEL>",
    "<SPREADSHEET_LABEL>",
    "<LABEL>",
    "<INDEX>",
    "<LETTER>",
    "<X_FUNC>",
    "<Y_FUNC>",
    "<Z_FUNC>",
    "<COS_FUNC>",
    "<SIN_FUNC>",
    "<TAN_FUNC>",
    "<ACOS_FUNC>",
    "<ASIN_FUNC>",
    "<ATAN_FUNC>",
    "<COSH_FUNC>",
    "<SINH_FUNC>",
    "<TANH_FUNC>",
    "<ACOSH_FUNC>",
    "<ASINH_FUNC>",
    "<ATANH_FUNC>",
    "<EXP_FUNC>",
    "<LOG_FUNC>",
    "\"ld(\"",
    "\"lg(\"",
    "<SQRT_FUNC>",
    "\"cbrt(\"",
    "<ABS_FUNC>",
    "<SGN_FUNC>",
    "<FLOOR_FUNC>",
    "<CEIL_FUNC>",
    "<ROUND_FUNC>",
    "<GAMMA_FUNC>",
    "\"random()\"",
    "<FUNCTION_LABEL>",
    "<TEXT>",
    "<CHAR>",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"(\"",
  };

}
