#!/bin/sh
WIXDIR=../wix

test -r $WIXDIR/candle.exe || {
 echo WiX is not installed into $WIXDIR
 exit 1
 }
 
WINEVERSION=`wine --version | sed s/"\."/""/g | sed s/wine\-//`

if [ "$WINEVERSION" -lt "1320" ]; then
 echo Wine is almost surely too old to run this program, get at least 1.3.20
 exit 2
 fi

test -r ../../../../build/debug/geogebra.jar || {
 echo GeoGebra does not seem to be built, run ../../buildggb40 first
 }

cp ../../../../build/debug/* .
cp ../../../../icons/hicolor/32x32/apps/geogebra.png .
cp ../../../../installer/geogebra.ico .

GGBVERSION=`cat ../../../../build/unpacked/version.txt`
GGBVERSION_DASHED=`echo $GGBVERSION | tr . -`
MSIFILE=GeoGebra-Windows-Installer-$GGBVERSION_DASHED.msi

wine $WIXDIR/candle.exe GeoGebra.wxs
wine $WIXDIR/light.exe -sval -ext WixUIExtension GeoGebra.wixobj

mv GeoGebra.msi $MSIFILE

echo "Now you can run 'msiexec /i $MSIFILE' to test GeoGebra Windows Installer on Unix"

