#!/bin/sh

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf"
 exit 1
 }
. ./autobuild.conf
cd $SVNDIR
svn co --accept theirs-full http://www.geogebra.org/svn/trunk/geogebra
cd geogebra
cp /usr/lib/jvm/java-1.5.0-sun/jre/lib/rt.jar ../java150-rt.jar
cp $P12DIR/igi-keystore.p12 ..
