#!/bin/sh
# Deploys numbered version of GeoGebra into directory 4.0
# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Start and loading configuration
date
echo "$0: start"

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf
cd $SVNDIR/geogebra

# 2. Setting local variables
MYVER=`cat build/unpacked/version.txt`
MYDIR=4.0

# 3. (Re)creating $WWWDIR/$MYDIR directory
if [ "$WWWDIR" = "" ]; then
 echo "Fatal error, WWWDIR=$WWWDIR, exiting for safety reasons"
 exit 2
 fi
cd build
echo "$0: (re)creating $WWWDIR/$MYDIR directory"
mkdir -p $WWWDIR/$MYDIR || exit 3
chmod g+rwx $WWWDIR/$MYDIR || exit 3

# 4. Copying JAR files to 4.0 and history/$MYVER:
rm -fR $WWWDIR/history/$MYVER || exit 4
mkdir -p $WWWDIR/history/$MYVER || exit 4
chmod g+rwx $WWWDIR/history/$MYVER || exit 4
find . -name '*.jar' -or -name '*.jar.pack.gz' | while read filename; do
 directory=`dirname $filename`
 mkdir -p $WWWDIR/$MYDIR/$directory $WWWDIR/history/$MYVER/$directory || exit 5
 chmod g+rwx $WWWDIR/$MYDIR/$directory $WWWDIR/history/$MYVER/$directory || exit 5
 cp $filename $WWWDIR/$MYDIR/$filename || exit 6
 cp $filename $WWWDIR/history/$MYVER/$filename || exit 6
 done
echo "$0: JAR files copied to 4.0 and history/$MYVER"

# 5. Finally, making sure that all files have group writable permissions:
chmod -R g+rw $WWWDIR/MYDIR $WWWDIR/history

# 6. Sending an email to geogebra-dev:
echo "New version of GeoGebra 4.0 has just been uploaded: $MYVER
Automatic message, do not reply" | mail -s "deployggb40 report" geogebra-dev@googlegroups.com || exit 7

date
echo "$0: end"
