#!/bin/sh
# Makes a diff on two sets of JAR files.
# Usage: put the different versions into VER1/DIR and VER2/DIR and edit the variables below.
# Then run this script.
# @author Zoltan Kovacs <zoltan@geogebra.org>

VER1=test40
VER2=test40a
DIR=unpacked

# Please stop editing here.

THISWD=`pwd`

rm -fR /tmp/diff-all
cd $VER1/$DIR
for i in *.jar; do
 for j in $VER1 $VER2; do
  mkdir -p /tmp/diff-all/$j/$DIR/$i
  cp $THISWD/$j/$DIR/$i /tmp/diff-all/$j/$DIR/$i
  cd /tmp/diff-all/$j/$DIR/$i
  unzip $i >/dev/null 2>&1
  done
 cd /tmp/diff-all/$VER1/$DIR/$i
 find . -type f | grep -v 'jar$' | while read FILENAME; do
  diff $FILENAME /tmp/diff-all/$VER2/$DIR/$i/$FILENAME >/dev/null 2>&1 || echo "$i/$FILENAME differs"
  done
 done
