#!/bin/sh
# Creates "vanilla" JARs into ../../build for testing purposes.
# No cleanup is done before compilation. To force cleaning up first,
# see the ant targets in ./update.

# This file has been created by using ./update.
# WORK IN PROGRESS

# 1. Start and loading configuration
test -r autobuild.conf || {
 echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf
cd $SVNDIR/geogebra

umask 0002 # trying to ensure g+w rights for all created files automatically

# 3. Setting global variables
export JAVA_HOME
export JDK_HOME=$JAVA_HOME
export JAVACMD=$JAVA_HOME/bin/java
export ANT_OPTS="-Xmx1024m"

# 4. Building

# 4/2. Setting classpath for ecj (required for Java 5)
CP=""
for i in *.jar; do
 CP=$CP:$i
 done
CP=$CP:3D/jogl.jar:3D/gluegenrt.jar

# 4/3. Setting bootclasspath
BCP=../java150-rt.jar

# 4/4. Creating *.class files
echo "$0: Creating class files"
$JAVACMD $ANT_OPTS -jar ecj-3.6.2.jar -1.5 -source 1.5 -target 1.5 -classpath $CP -bootclasspath $BCP\
 -time -proceedOnError -g .  > .ecjlog 2>&1
tail -1 .ecjlog
echo ", see .ecjlog for more details" # .ecjlog has no \n before EOF

# 4/5. Packaging
ant ggb-jar-files || exit 3
