#!/bin/sh
# Pushes files to be deployed towards all mirror servers.
# To use it, set up remote mirror servers with a web server (lighttpd for example),
# create an ssh login there, and create an private/public key-pair by using ssh-keygen.
# Copy the public part to the remote machine by adding it to .ssh/authorized_keys2.
# This will provide automatic file copying between the host running this script
# and the remote machine.
# Edit details for each mirror server in mirrors.conf.
# The remote server must ensure that http://$IP/webstart
# is the same directory as "ssh -p $PORT $RUSER@$IP; cd $DIR".

# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Start and loading configuration
date
echo "$0: start"

test -r autobuild.conf || {
 echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

# 2. Setting local variables
MYDIR=4.2
cd $WWWDIR/$MYDIR
MYVER=`cat unpacked/version.txt`

cat $SVNDIR/geogebra/scripts/autobuild/mirrors.conf | grep -v "^#" | grep -v "^$" | while read IP PORT RUSER DIR; do
 echo "Copying files to $RUSER@$IP:$PORT/$DIR..."
 # (Re)creating directories (-n is important to prevent reading data from cat):
 ssh -n -l $RUSER -p $PORT $IP "mkdir -p $DIR; cd $DIR; mkdir -p $MYDIR; cd $MYDIR; mkdir -p minimal unsigned usb"
 # Copying files to root directory:
 scp -P $PORT forum.gif wiki.jpg geogebra64.gif packed/*.jar.pack.gz unpacked/*.jnlp unpacked/*.jar $RUSER@$IP:$DIR/$MYDIR
 # All JNLP files will be packEnabled on the remote servers (assuming no mod_negotiation is enabled):
 ssh -n -l $RUSER -p $PORT $IP "cd $DIR/$MYDIR; find -name '*.jnlp' |\
  xargs sed -i s/\"<resources>\"/\"<resources> <property name=\\\"jnlp.packEnabled\\\" value=\\\"true\\\"\/>\"/g"
 # Copying files to unsigned/ directory:
 scp -P $PORT unsigned/unpacked/*.jar unsigned/packed/*.jar.pack.gz $RUSER@$IP:$DIR/$MYDIR/unsigned
 # Copying files to minimal/ directory:
 # This would be somewhat slower due to bandwith usage:
 # "scp -P $PORT minimal/*.jar minimal/*.html $RUSER@$IP:$DIR/$MYDIR/minimal"
 # So we copy the files on the remote machine instead:
 ssh -n -l $RUSER -p $PORT $IP "cd $DIR/$MYDIR; cp unsigned/geogebra.jar unsigned/geogebra_main.jar minimal"
 scp -P $PORT minimal/*.html $RUSER@$IP:$DIR/$MYDIR/minimal
 # Copying files to usb/ directory:
 scp -P $PORT usb/*.jar $RUSER@$IP:$DIR/$MYDIR/usb

 # TODO: Automatic check (by wget)

 done

date
echo "$0: end"
