#!/bin/sh
# Updates GeoGebra from SVN repository
# @author Zoltan Kovacs <zoltan@geogebra.org>

# Run "./update --no-update" option for autobuild if you want to force web content update
# even if no new commit exists the repository.

if [ "$0" != "./update" -a "$0" != "./buildggb40" ]; then
 echo "Usage:
  ./buildggb40 [revision]  Compiles and installs numbered version into test40
  ./update [--no-update]   Compiles and installs autobuild into test40a"
  exit 1
  fi

# 1. Start and loading configuration
date
echo "$0: start"

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf
cd $SVNDIR/geogebra

umask 0002 # trying to ensure g+w rights for all created files automatically

if [ "$0" = "./buildggb40" -a "$1" != "" ]; then
 REVISION_PARAM=" -r $1 "
 echo "Using revision $1"
 fi

# 2. Updating source files
if [ "$0" = "./update" -a "$1" != "--no-update" ]; then
 $SVN_COMMAND $REVISION_PARAM update --accept theirs-full --force | tail -1 | grep ^At && exit 1 # No updates found.
 echo "$0: new commit was found in repository"
else
 rm -fR org # not sure why SVN cannot handle this properly (org/mathpiper), http://stackoverflow.com/questions/1608836/folders-skipped-when-updating-svn
 ant delete-sources
 $SVN_COMMAND $REVISION_PARAM update --accept theirs-full --force
 fi
$SVN_COMMAND info | grep Revision | awk '{print $2}' > scripts/autobuild/.revision
WARNINGS=`chmod -R g+rw $SVNDIR/geogebra 2>&1 | wc -l | awk '{print $1}'`
echo "$WARNINGS warnings during chmod'ing source files"

# 3. Setting global variables
export JAVA_HOME
export JDK_HOME=$JAVA_HOME
export JAVACMD=$JAVA_HOME/bin/java
export ANT_OPTS="-Xmx1024m"

# 4. Building

# 4/1. Deleting *.class files and compiling grammar with javacc
ant delete-classes compile-grammar-cl || exit 3

# 4/2. Setting classpath for ecj (required for Java 5)
CP=""
for i in *.jar; do
 CP=$CP:$i
 done
CP=$CP:3D/jogl.jar:3D/gluegenrt.jar

# 4/3. Setting bootclasspath
BCP=../java150-rt.jar

# 4/4. Creating *.class files
echo "Creating class files"
$JAVACMD $ANT_OPTS -jar ecj-3.6.2.jar -1.5 -source 1.5 -target 1.5 -classpath $CP -bootclasspath $BCP\
 -time -proceedOnError -g .  > .ecjlog 2>&1
tail -1 .ecjlog
echo ", see .ecjlog for more details" # .ecjlog has no \n before EOF

# 4/5. Packaging
ant geogebra || exit 3

# 4/6. Testing packed jars
cd $SVNDIR/geogebra/scripts/autobuild
./test-packed-jars
cd $SVNDIR/geogebra

# 4/7. Creating Mac OS X installer
ant installer-clean installer-macosx

# Making sure that all files have group writable permissions
WARNINGS=`chmod -R g+rw $SVNDIR/geogebra 2>&1 | wc -l | awk '{print $1}'`
echo "$WARNINGS warnings during chmod'ing build files"

# 5. Setting local variables
MYVER=`cat build/unpacked/version.txt`
if [ "$0" = "./update" ]; then
 MYDIR=test40a
 MYVER=autobuild
 fi
if [ "$0" = "./buildggb40" ]; then
 MYDIR=test40
 fi

if [ "$MYDIR" = "" -o "$WWWDIR" = "" ]; then
 echo "Fatal error, MYDIR=$MYDIR, WWWDIR=$WWWDIR, exiting for safety reasons"
 exit 2
 fi

# 6. Copying and text replacing
cd build
if [ "$MYDIR" != "4.0" ]; then
 rm -fR $WWWDIR/$MYDIR || exit 4 # Be careful!
 fi
mkdir -p $WWWDIR/$MYDIR || exit 4
chmod g+rwx $WWWDIR/$MYDIR || exit 4

echo "$0: (re)creating $WWWDIR/$MYDIR directory"

# 6/1. Copying dynamically generated files (autobuild)
cp -R * $WWWDIR/$MYDIR || exit 4
echo "$0: dynamically generated files copied"

# 6/2. Copying static files
cp -R $SVNDIR/geogebra/webstart/4.0/* $WWWDIR/$MYDIR || exit 4
cp $SVNDIR/geogebra/vernier_ccsd-macintel-static.jar $WWWDIR/$MYDIR || exit 4
echo "$0: static files copied"

# 6/3. Moving *.html and *.jnlp to unpacked/ and rewriting static URLs:
# http://www.geogebra.org/webstart/4.0/unsigned -> http://www.geogebra.org/webstart/$MYDIR/unsigned/unpacked
# http://www.geogebra.org/webstart/4.0/usb-gomotion.ggb -> http://www.geogebra.org/webstart/$MYDIR/usb-gomotion.ggb
# http://www.geogebra.org/webstart/4.0/debug -> http://www.geogebra.org/webstart/$MYDIR/debug
# http://www.geogebra.org/webstart/4.0/ -> http://www.geogebra.org/webstart/$MYDIR/unpacked/
# </title> -> ($MYVER) </title>

# In addition, removing those lines which have the "association mime-type" text.

cd $WWWDIR/$MYDIR
for i in *.html *.jnlp; do
    cat $i | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.0\/unsigned"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/unsigned\/unpacked"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.0\/usb-gomotion"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/usb-gomotion.ggb"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.0\/debug"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/debug"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.0\/"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/unpacked"/g | \
     sed s/"<\/title>"/" ($MYVER)<\/title>"/g | \
     grep -v "association mime-type" \
     > unpacked/$i
    rm $i || exit 4
    cp unpacked/$i $i || exit 4 # Some files in some subdirectories may still refer to the original file.
    echo "$0: $i is rewritten"
    done

# 7. Finally, making sure that all files have group writable permissions
WARNINGS=`chmod -R g+rw $WWWDIR/$MYDIR 2>&1 | wc -l | awk '{print $1}'`
echo "$WARNINGS warnings during chmod'ing web files"

date
echo "$0: end"
