#!/bin/sh
# Updates GeoGebra from SVN repository
# @author Zoltan Kovacs <zoltan@geogebra.org>

# Run "./update --no-update" option for autobuild if you want to force web content update
# even if no new commit exists the repository.

if [ "$0" != "./update" -a "$0" != "./buildggb40" ]; then
 echo "Usage:
  ./buildggb40             Compiles and installs numbered version into test40
  ./update [--no-update]   Compiles and installs autobuild into test40a"
  exit 1
  fi

# 1. Start and loading configuration
date
echo "$0: start"

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf
cd $SVNDIR/geogebra

# 2. Updating source files
if [ "$0" = "./update" -a "$1" != "--no-update" ]; then
 $SVN_COMMAND update --accept theirs-full --force | tail -1 | grep ^At && exit 1 # No updates found.
 echo "$0: new commit was found in repository"
else
 $SVN_COMMAND update --accept theirs-full --force
 fi
chmod -R g+rw $SVNDIR/geogebra

# 3. Setting global variables
export JAVA_HOME
export ANT_OPTS="-Xmx1024m"

# 4. Building
# alias signjar=jarsigner # May be needed for ant version < 1.8.0 (the "executable" attribute is not supported yet).
ant -f build.xml geogebra-cl || exit 3
chmod -R g+rw build

# 5. Setting local variables
MYVER=`cat build/unpacked/version.txt`
if [ "$0" = "./update" ]; then
 MYDIR=test40a
 MYVER=autobuild
 fi
if [ "$0" = "./buildggb40" ]; then
 MYDIR=test40
 fi

if [ "$MYDIR" = "" -o "$WWWDIR" = "" ]; then
 echo "Fatal error, MYDIR=$MYDIR, WWWDIR=$WWWDIR, exiting for safety reasons"
 exit 2
 fi

# 6. Copying and text replacing
cd build
if [ "$MYDIR" != "4.0" ]; then
 rm -fR $WWWDIR/$MYDIR || exit 4 # Be careful!
 fi
mkdir -p $WWWDIR/$MYDIR || exit 4
chmod g+rwx $WWWDIR/$MYDIR || exit 4

echo "$0: (re)creating $WWWDIR/$MYDIR directory"

# 6/1. Copying dynamically generated files (autobuild):
cp -R * $WWWDIR/$MYDIR || exit 4
echo "$0: dynamically generated files copied"

# 6/2. Copying static files:
cp -R $SVNDIR/geogebra/webstart/4.0/* $WWWDIR/$MYDIR || exit 4
cp $SVNDIR/geogebra/vernier_ccsd-macintel-static.jar $WWWDIR/$MYDIR || exit 4
echo "$0: static files copied"

# 6/3. Moving *.html and *.jnlp to unpacked/ and rewriting static URLs:
# http://www.geogebra.org/webstart/4.0/unsigned -> http://www.geogebra.org/webstart/$MYDIR/unsigned/unpacked
# http://www.geogebra.org/webstart/4.0/usb-gomotion.ggb -> http://www.geogebra.org/webstart/$MYDIR/usb-gomotion.ggb
# http://www.geogebra.org/webstart/4.0/debug -> http://www.geogebra.org/webstart/$MYDIR/debug
# http://www.geogebra.org/webstart/4.0/ -> http://www.geogebra.org/webstart/$MYDIR/unpacked/
# </title> -> ($MYVER) </title>

# In addition, removing those lines which have the "association mime-type" text.

cd $WWWDIR/$MYDIR
for i in *.html *.jnlp; do
    cat $i | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.0\/unsigned"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/unsigned\/unpacked"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.0\/usb-gomotion"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/usb-gomotion.ggb"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.0\/debug"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/debug"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.0\/"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/unpacked"/g | \
     sed s/"<\/title>"/" ($MYVER)<\/title>"/g | \
     grep -v "association mime-type" \
     > unpacked/$i
    rm $i || exit 4
    cp unpacked/$i $i || exit 4 # Some files in some subdirectories may still refer to the original file.
    echo "$0: $i is rewritten"
    done

date
echo "$0: end"
