#!/bin/sh

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf"
 exit 1
 }
. ./autobuild.conf
NOW=`date +%Y%m%d-%H%M`
cd $SVNDIR/geogebra
if [ "$1" != "--no-update" ]; then
    svn update --accept theirs-full | tail -1 | grep ^At && exit 0 # No updates found.
    fi
export JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
alias signjar=jarsigner # Needed for ant version < 1.8.0 (the "executable" attribute is not supported yet).
ant -f build-cl.xml
cd build
COPYDIR=$WWWDIR/$NOW
mkdir -p $COPYDIR
cp -a * $COPYDIR
