#!/bin/sh
# Creates zip files for geogebratube from SVN repository
# @author Zoltan Kovacs <zoltan@geogebra.org>

ZIPDIR=/Users/zoltan/source/translation/gui
DATE=`date +%Y%m%d`
ZIPFILE=geogebratube_prop_40_$DATE.zip
REPO=file:///opt/repos/tube/trunk # not used yet, but assumed
SVNDIR=/Users/zoltan/svn/tube

date
echo "$0: start"

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

cd $SVNDIR/tube/trunk/languages
$SVN_COMMAND update --accept theirs-full --force
zip $ZIPFILE *.properties
mv $ZIPFILE $ZIPDIR

date
echo "$0: end"
