#!/bin/sh
# Creates a .zip file with error report, containing the erroneous GGBs,
# their required output and the diffs.
# First a full regression test (./runtests) is required.
# Example: ./create-error-report

DEVEL_VERSION=`cd devel-jars; java -jar geogebra.jar --v | awk '{print $2}'`
TARGET_DIR=error-report-$DEVEL_VERSION
rm -fR $TARGET_DIR

cp -a tmp $TARGET_DIR

cd $TARGET_DIR

find -name '*.err' -print0 | xargs -0 rm
find -name '*.out' -print0 | xargs -0 rm
find -name '*.diff' -size 0 -print0 | xargs -0 rm
find -name '*.diff' -exec ../copy-erroneous-ggb '{}' ';'

# Removing empty directories:
find -type d -empty -print0 | xargs -0 rmdir
