#!/bin/sh
# Runs a test.
# Example: ./runtest path/example1.ggb
# This will run path/example1.ggb in directory tmp and compare the output tmp/path/example1.out by path/example1.out.
# Return code is also important.

test -x ./runtest || {
 echo "$0 should be run within its directory, exiting"
 exit 255
 }

G=devel-jars/geogebra.jar
test -r $G || {
 echo "$G is missing, exiting (please compile GeoGebra JARs first and copy it to devel-jars)"
 exit 254
 }

mkdir -p tmp || {
 echo "Cannot create tmp directory, exiting"
 exit 253
 }

if [ $# -ne 1 ]; then
 echo "Invalid number of parameters (1 is needed), exiting"
 exit 252
 fi

T="$1"
test -r "$T" || {
 echo "No test named $T, exiting"
 exit 251
 }

D=`dirname "$1"`
O=$D/`basename "$1" .ggb`.out
test -r "$O" || {
 echo "No output for test $T, exiting"
 exit 250
 }

mkdir -p tmp/"$D" || {
 echo "Cannot create tmp directory, exiting"
 exit 253
 }

echo -n "testing $T..."
cd devel-jars
timeout -k 10 10 java -jar geogebra.jar --showSplash=false --regressionFile=../tmp/"$O" ../"$T" >../tmp/"$O".err 2>&1
cd ..

R=$?
OK=0
RV=0

diff -u "$O" tmp/"$O" > tmp/"$O".diff && OK=1

# Summary (not configured yet for GeoGebra)
if [ $R = 0 ]; then
 echo -n " runs ok, "
 else
  if [ $R = 126 ]; then
   echo -n " exits with error code 126, "
   else
    if [ $R = 134 ]; then
     echo -n " exits with error code 134, "
     else
      if [ $R = 255 ]; then
       echo -n " exits with error code 255/-1 (illegal input, ok), "
       else
        echo -n " exits with error code $R (non-standard), "
       fi
     fi
   fi
 fi

if [ $OK = 1 ]; then
 echo "outputs ok"
 G=`cat .good`
 G=`expr $G + 1`
 echo $G > .good
 else
 echo "outputs differ"
 B=`cat .bad`
 B=`expr $B + 1`
 echo $B > .bad
 RV=1
 fi

exit $RV
