#!/bin/sh
# Runs all tests.
# Example: ./runtests

test -x ./runtests || {
 echo "$0 should be run within its directory, exiting"
 exit 255
 }

echo 0 > .good
echo 0 > .bad

find tests/ -name '*.ggb' -exec ./runtest "{}" ';'

G=`cat .good`
B=`cat .bad`
N=`expr $G + $B`

echo "
Summary: $G good and $B bad from $N tests"
