/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package geogebra.algebra.parser;
import geogebra.*;
import geogebra.kernel.*;
import geogebra.kernel.arithmetic.*;
import java.util.*;

public class ParserTokenManager implements ParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active1 & 0x6L) != 0L)
         {
            jjmatchedKind = 46;
            return 61;
         }
         if ((active0 & 0x6038000000000L) != 0L)
            return 284;
         if ((active0 & 0x40L) != 0L)
            return 0;
         if ((active0 & 0x2000L) != 0L)
            return 15;
         if ((active0 & 0x1000000L) != 0L)
            return 9;
         if ((active0 & 0x1000L) != 0L)
            return 12;
         if ((active0 & 0x40000L) != 0L)
            return 6;
         if ((active1 & 0x10L) != 0L)
         {
            jjmatchedKind = 46;
            return 125;
         }
         if ((active0 & 0x800000000L) != 0L || (active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 46;
            return 38;
         }
         return -1;
      case 1:
         if ((active0 & 0x800000000L) != 0L || (active1 & 0x816L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 284;
         }
         return -1;
      case 2:
         if ((active0 & 0x800000000L) != 0L)
            return 284;
         if ((active1 & 0x810L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 2;
            return 284;
         }
         return -1;
      case 3:
         if ((active1 & 0x810L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 3;
            return 284;
         }
         return -1;
      case 4:
         if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 4;
            return 284;
         }
         return -1;
      case 5:
         if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 5;
            return 284;
         }
         return -1;
      case 6:
         if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 6;
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjStartNfaWithStates_0(0, 24, 9);
      case 39:
         return jjStopAtPos(0, 36);
      case 40:
         return jjStopAtPos(0, 86);
      case 41:
         return jjStopAtPos(0, 85);
      case 43:
         return jjStopAtPos(0, 19);
      case 44:
         return jjStopAtPos(0, 81);
      case 45:
         return jjStopAtPos(0, 20);
      case 47:
         return jjStopAtPos(0, 22);
      case 58:
         return jjStopAtPos(0, 79);
      case 59:
         return jjStopAtPos(0, 5);
      case 60:
         return jjStartNfaWithStates_0(0, 12, 12);
      case 61:
         return jjStartNfaWithStates_0(0, 18, 6);
      case 62:
         return jjStartNfaWithStates_0(0, 13, 15);
      case 88:
         return jjStartNfaWithStates_0(0, 41, 284);
      case 91:
         return jjStopAtPos(0, 80);
      case 93:
         return jjStopAtPos(0, 82);
      case 94:
         return jjStopAtPos(0, 23);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x6L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x800000000L, 0x800L);
      case 120:
         jjmatchedKind = 39;
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x0L);
      case 121:
         jjmatchedKind = 40;
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 83);
      case 124:
         return jjStartNfaWithStates_0(0, 6, 0);
      case 125:
         return jjStopAtPos(0, 84);
      case 172:
         return jjStopAtPos(0, 7);
      case 176:
         return jjStopAtPos(0, 33);
      case 178:
         return jjStopAtPos(0, 26);
      case 179:
         return jjStopAtPos(0, 27);
      case 8308:
         return jjStopAtPos(0, 28);
      case 8309:
         return jjStopAtPos(0, 29);
      case 8310:
         return jjStopAtPos(0, 30);
      case 8495:
         return jjStopAtPos(0, 32);
      case 8734:
         return jjStopAtPos(0, 34);
      case 8741:
         return jjStopAtPos(0, 16);
      case 8869:
         return jjStopAtPos(0, 17);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 49);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L, active1, 0x800L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2L);
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 40:
         if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(2, 65);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(2, 66);
         break;
      case 100:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(2, 35, 284);
         break;
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, 0L, active1);
      return 3;
   }
   switch(curChar)
   {
      case 100:
         return jjMoveStringLiteralDfa4_0(active1, 0x800L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active1, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(2, 0L, active1);
}
private final int jjMoveStringLiteralDfa4_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(2, 0L, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, 0L, active1);
      return 4;
   }
   switch(curChar)
   {
      case 40:
         if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(4, 68);
         break;
      case 111:
         return jjMoveStringLiteralDfa5_0(active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(3, 0L, active1);
}
private final int jjMoveStringLiteralDfa5_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(3, 0L, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, 0L, active1);
      return 5;
   }
   switch(curChar)
   {
      case 109:
         return jjMoveStringLiteralDfa6_0(active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(4, 0L, active1);
}
private final int jjMoveStringLiteralDfa6_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(4, 0L, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, 0L, active1);
      return 6;
   }
   switch(curChar)
   {
      case 40:
         return jjMoveStringLiteralDfa7_0(active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(5, 0L, active1);
}
private final int jjMoveStringLiteralDfa7_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(5, 0L, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, 0L, active1);
      return 7;
   }
   switch(curChar)
   {
      case 41:
         if ((active1 & 0x800L) != 0L)
            return jjStopAtPos(7, 75);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, 0L, active1);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x10000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec1 = {
   0x8000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec2 = {
   0x0L, 0x80000000L, 0x0L, 0x0L
};
static final long[] jjbitVec3 = {
   0x0L, 0x100000000L, 0x0L, 0x0L
};
static final long[] jjbitVec4 = {
   0x0L, 0x1000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec5 = {
   0x0L, 0x2000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec6 = {
   0x0L, 0x0L, 0x0L, 0x20L
};
static final long[] jjbitVec7 = {
   0x0L, 0x0L, 0x0L, 0x2000000000000000L
};
static final long[] jjbitVec8 = {
   0x0L, 0x0L, 0x0L, 0x1L
};
static final long[] jjbitVec9 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec11 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec12 = {
   0x1600L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec13 = {
   0x0L, 0xffc000000000L, 0x0L, 0xffc000000000L
};
static final long[] jjbitVec14 = {
   0x0L, 0x3ff00000000L, 0x0L, 0x3ff000000000000L
};
static final long[] jjbitVec15 = {
   0x0L, 0xffc000000000L, 0x0L, 0xff8000000000L
};
static final long[] jjbitVec16 = {
   0x0L, 0xffc000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec17 = {
   0x0L, 0x3ff0000L, 0x0L, 0x3ff0000L
};
static final long[] jjbitVec18 = {
   0x0L, 0x3ffL, 0x0L, 0x0L
};
static final long[] jjbitVec19 = {
   0x600007fffffc0L, 0xffffffffffffc000L, 0xffffffffffffffffL, 0x13000000007fffffL
};
static final long[] jjbitVec20 = {
   0x0L, 0x0L, 0x80000000000000L, 0xffffffffff7fffffL
};
static final long[] jjbitVec21 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xfffffffffffffff0L
};
static final long[] jjbitVec22 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x1ffffffffffL, 0x0L
};
static final long[] jjbitVec23 = {
   0x0L, 0x0L, 0xfffffffffffe0000L, 0xfffffffffffffL
};
static final long[] jjbitVec24 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffff0003L, 0x3ffffffffffffffL
};
static final long[] jjbitVec25 = {
   0xfffe000000000000L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec26 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0x1fffffffffffffffL
};
static final long[] jjbitVec27 = {
   0x0L, 0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec28 = {
   0xffffffffffffffffL, 0xffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec29 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xfffffffffL, 0x0L
};
static final long[] jjbitVec30 = {
   0xffffffffe0000000L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec31 = {
   0x3fffffffffffL, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec32 = {
   0xfffffffffff80000L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec33 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xfffffffffffffffL
};
static final long[] jjbitVec34 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0x1fffffffffffffffL
};
static final long[] jjbitVec35 = {
   0x0L, 0xffffffc000000000L, 0xfffffffe3fffffffL, 0x1fffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 284;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 38:
                  if ((0x3ff008000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 40)
                  {
                     if (kind > 76)
                        kind = 76;
                  }
                  if ((0x3ff008000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  break;
               case 61:
                  if ((0x3ff008000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 40)
                  {
                     if (kind > 76)
                        kind = 76;
                  }
                  if ((0x3ff008000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  break;
               case 125:
                  if ((0x3ff008000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 40)
                  {
                     if (kind > 76)
                        kind = 76;
                  }
                  if ((0x3ff008000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  break;
               case 284:
                  if ((0x3ff008000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 40)
                  {
                     if (kind > 76)
                        kind = 76;
                  }
                  if ((0x3ff008000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 42)
                        kind = 42;
                     jjCheckNAddStates(7, 15);
                  }
                  else if (curChar == 46)
                     jjCheckNAddTwoStates(101, 102);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(57, 58);
                  else if (curChar == 42)
                  {
                     if (kind > 21)
                        kind = 21;
                  }
                  else if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 9;
                  else if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 3;
                  else if (curChar == 63)
                  {
                     if (kind > 25)
                        kind = 25;
                  }
                  break;
               case 3:
                  if (curChar == 38 && kind > 9)
                     kind = 9;
                  break;
               case 4:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if (curChar == 61 && kind > 10)
                     kind = 10;
                  break;
               case 7:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  if (curChar == 61 && kind > 11)
                     kind = 11;
                  break;
               case 10:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 12:
                  if (curChar == 61 && kind > 14)
                     kind = 14;
                  break;
               case 13:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 15:
                  if (curChar == 61 && kind > 15)
                     kind = 15;
                  break;
               case 16:
                  if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if (curChar == 42 && kind > 21)
                     kind = 21;
                  break;
               case 19:
                  if (curChar == 63 && kind > 25)
                     kind = 25;
                  break;
               case 24:
                  if (curChar == 40 && kind > 63)
                     kind = 63;
                  break;
               case 31:
                  if (curChar == 40 && kind > 64)
                     kind = 64;
                  break;
               case 34:
                  if (curChar == 40 && kind > 73)
                     kind = 73;
                  break;
               case 45:
                  if (curChar == 40 && kind > 74)
                     kind = 74;
                  break;
               case 56:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(57, 58);
                  break;
               case 57:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(57, 58);
                  break;
               case 58:
                  if (curChar == 34 && kind > 77)
                     kind = 77;
                  break;
               case 67:
                  if (curChar == 40 && kind > 53)
                     kind = 53;
                  break;
               case 70:
                  if (curChar == 40 && kind > 59)
                     kind = 59;
                  break;
               case 87:
                  if (curChar == 40 && kind > 71)
                     kind = 71;
                  break;
               case 100:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(101, 102);
                  break;
               case 101:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(101);
                  break;
               case 102:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(102, 103);
                  break;
               case 104:
                  if (curChar == 45)
                     jjCheckNAdd(105);
                  break;
               case 105:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAdd(105);
                  break;
               case 107:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(4, 6);
                  break;
               case 109:
                  if ((0xfffffffbffffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(110);
                  break;
               case 110:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(110);
                  break;
               case 112:
                  jjAddStates(16, 17);
                  break;
               case 114:
                  if ((0x3ff008000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 116:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 117:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 118:
                  if (curChar == 40 && kind > 76)
                     kind = 76;
                  break;
               case 120:
                  jjAddStates(18, 19);
                  break;
               case 123:
                  if (curChar == 40 && kind > 51)
                     kind = 51;
                  break;
               case 126:
                  if (curChar == 40 && kind > 57)
                     kind = 57;
                  break;
               case 130:
                  if (curChar == 40 && kind > 72)
                     kind = 72;
                  break;
               case 144:
                  if (curChar == 40 && kind > 52)
                     kind = 52;
                  break;
               case 147:
                  if (curChar == 40 && kind > 58)
                     kind = 58;
                  break;
               case 151:
                  if (curChar == 40 && kind > 67)
                     kind = 67;
                  break;
               case 155:
                  if (curChar == 40 && kind > 70)
                     kind = 70;
                  break;
               case 174:
                  if (curChar == 40 && kind > 54)
                     kind = 54;
                  break;
               case 180:
                  if (curChar == 40 && kind > 55)
                     kind = 55;
                  break;
               case 186:
                  if (curChar == 40 && kind > 56)
                     kind = 56;
                  break;
               case 192:
                  if (curChar == 40 && kind > 60)
                     kind = 60;
                  break;
               case 199:
                  if (curChar == 40 && kind > 61)
                     kind = 61;
                  break;
               case 206:
                  if (curChar == 40 && kind > 62)
                     kind = 62;
                  break;
               case 213:
                  if (curChar == 40 && kind > 69)
                     kind = 69;
                  break;
               case 273:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddStates(7, 15);
                  break;
               case 274:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddTwoStates(274, 275);
                  break;
               case 275:
                  if (curChar == 46)
                     jjCheckNAdd(276);
                  break;
               case 276:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(276);
                  break;
               case 277:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(277, 278);
                  break;
               case 278:
                  if (curChar == 46 && kind > 42)
                     kind = 42;
                  break;
               case 279:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(20, 22);
                  break;
               case 280:
                  if (curChar == 46)
                     jjCheckNAdd(281);
                  break;
               case 281:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(281, 103);
                  break;
               case 282:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(282, 283);
                  break;
               case 283:
                  if (curChar == 46)
                     jjCheckNAdd(103);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 38:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  else if (curChar == 95)
                     jjAddStates(23, 24);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 95)
                     jjAddStates(25, 26);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 61:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  else if (curChar == 95)
                     jjAddStates(23, 24);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 95)
                     jjAddStates(25, 26);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if (curChar == 110)
                     jjCheckNAdd(31);
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 125:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  else if (curChar == 95)
                     jjAddStates(23, 24);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 95)
                     jjAddStates(25, 26);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 132;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 128;
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 284:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  else if (curChar == 95)
                     jjAddStates(23, 24);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 95)
                     jjAddStates(25, 26);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(27, 33);
                  }
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 0;
                  if (curChar == 97)
                     jjAddStates(34, 46);
                  else if (curChar == 65)
                     jjAddStates(47, 53);
                  else if (curChar == 83)
                     jjAddStates(54, 57);
                  else if (curChar == 115)
                     jjAddStates(58, 62);
                  else if (curChar == 67)
                     jjAddStates(63, 65);
                  else if (curChar == 99)
                     jjAddStates(66, 68);
                  else if (curChar == 70)
                     jjAddStates(69, 70);
                  else if (curChar == 102)
                     jjAddStates(71, 72);
                  else if (curChar == 84)
                     jjAddStates(73, 75);
                  else if (curChar == 116)
                     jjAddStates(76, 78);
                  else if (curChar == 108)
                     jjAddStates(79, 80);
                  else if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 54;
                  else if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 49;
                  else if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 43;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 38;
                  else if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if (curChar == 80)
                     jjCheckNAdd(20);
                  else if (curChar == 112)
                     jjCheckNAdd(20);
                  break;
               case 0:
                  if (curChar == 124 && kind > 8)
                     kind = 8;
                  break;
               case 20:
                  if (curChar == 105 && kind > 31)
                     kind = 31;
                  break;
               case 21:
                  if (curChar == 112)
                     jjCheckNAdd(20);
                  break;
               case 22:
                  if (curChar == 80)
                     jjCheckNAdd(20);
                  break;
               case 25:
               case 28:
                  if (curChar == 112)
                     jjCheckNAdd(24);
                  break;
               case 26:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 29:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 32:
                  if (curChar == 110)
                     jjCheckNAdd(31);
                  break;
               case 33:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 35:
               case 40:
                  if (curChar == 100)
                     jjCheckNAdd(34);
                  break;
               case 36:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 39:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 41:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 46:
               case 51:
                  if (curChar == 97)
                     jjCheckNAdd(45);
                  break;
               case 47:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 52:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 57:
                  jjAddStates(81, 82);
                  break;
               case 59:
                  if (curChar == 108)
                     jjAddStates(79, 80);
                  break;
               case 60:
                  if (curChar == 103)
                     jjCheckNAdd(31);
                  break;
               case 62:
                  if (curChar == 110)
                     jjCheckNAdd(31);
                  break;
               case 63:
                  if (curChar == 116)
                     jjAddStates(76, 78);
                  break;
               case 64:
                  if (curChar == 101 && kind > 37)
                     kind = 37;
                  break;
               case 65:
               case 75:
                  if (curChar == 117)
                     jjCheckNAdd(64);
                  break;
               case 66:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 68:
               case 77:
                  if (curChar == 110)
                     jjCheckNAdd(67);
                  break;
               case 69:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 71:
               case 79:
                  if (curChar == 104)
                     jjCheckNAdd(70);
                  break;
               case 72:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 84)
                     jjAddStates(73, 75);
                  break;
               case 76:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 78:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 80:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 102)
                     jjAddStates(71, 72);
                  break;
               case 83:
                  if (curChar == 101 && kind > 38)
                     kind = 38;
                  break;
               case 84:
               case 93:
                  if (curChar == 115)
                     jjCheckNAdd(83);
                  break;
               case 85:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 88:
               case 96:
                  if (curChar == 114)
                     jjCheckNAdd(87);
                  break;
               case 89:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 70)
                     jjAddStates(69, 70);
                  break;
               case 94:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 97:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 103:
                  if (curChar == 69)
                     jjAddStates(83, 84);
                  break;
               case 106:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(27, 33);
                  break;
               case 107:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(4, 6);
                  break;
               case 108:
                  if (curChar == 95)
                     jjAddStates(25, 26);
                  break;
               case 109:
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(110);
                  break;
               case 110:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(110);
                  break;
               case 111:
                  if (curChar == 123)
                     jjCheckNAdd(112);
                  break;
               case 112:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(112, 113);
                  break;
               case 113:
                  if (curChar != 125)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(110);
                  break;
               case 114:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 115:
                  if (curChar == 95)
                     jjAddStates(23, 24);
                  break;
               case 116:
                  jjCheckNAddTwoStates(117, 118);
                  break;
               case 117:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 119:
                  if (curChar == 123)
                     jjCheckNAdd(120);
                  break;
               case 120:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(120, 121);
                  break;
               case 121:
                  if (curChar == 125)
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 122:
                  if (curChar == 99)
                     jjAddStates(66, 68);
                  break;
               case 124:
               case 135:
                  if (curChar == 115)
                     jjCheckNAdd(123);
                  break;
               case 127:
               case 137:
                  if (curChar == 104)
                     jjCheckNAdd(126);
                  break;
               case 128:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 131:
               case 140:
                  if (curChar == 108)
                     jjCheckNAdd(130);
                  break;
               case 132:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 67)
                     jjAddStates(63, 65);
                  break;
               case 136:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 138:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 141:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 115)
                     jjAddStates(58, 62);
                  break;
               case 145:
               case 162:
                  if (curChar == 110)
                     jjCheckNAdd(144);
                  break;
               case 146:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 148:
               case 164:
                  if (curChar == 104)
                     jjCheckNAdd(147);
                  break;
               case 149:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 152:
               case 167:
                  if (curChar == 116)
                     jjCheckNAdd(151);
                  break;
               case 153:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 156:
               case 158:
               case 170:
                  if (curChar == 110)
                     jjCheckNAdd(155);
                  break;
               case 157:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 159:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 83)
                     jjAddStates(54, 57);
                  break;
               case 163:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 165:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 168:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 171:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 65)
                     jjAddStates(47, 53);
                  break;
               case 175:
               case 217:
               case 220:
                  if (curChar == 115)
                     jjCheckNAdd(174);
                  break;
               case 176:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 181:
               case 225:
               case 228:
                  if (curChar == 110)
                     jjCheckNAdd(180);
                  break;
               case 182:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 187:
               case 233:
               case 236:
                  if (curChar == 110)
                     jjCheckNAdd(186);
                  break;
               case 188:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 189:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 193:
               case 241:
               case 245:
                  if (curChar == 104)
                     jjCheckNAdd(192);
                  break;
               case 194:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 200:
               case 251:
               case 255:
                  if (curChar == 104)
                     jjCheckNAdd(199);
                  break;
               case 201:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 207:
               case 261:
               case 265:
                  if (curChar == 104)
                     jjCheckNAdd(206);
                  break;
               case 208:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 212:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 214:
               case 271:
                  if (curChar == 115)
                     jjCheckNAdd(213);
                  break;
               case 215:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 216:
                  if (curChar == 97)
                     jjAddStates(34, 46);
                  break;
               case 218:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 221:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 226:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 229:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 231:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 234:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 237:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 239:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 242:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 246:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 248:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 249:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 252:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 256:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 258:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 262:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 263:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 264:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 266:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 272:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 38:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(0, 3);
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 61:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(0, 3);
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 125:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(0, 3);
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 284:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(4, 6);
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(110);
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(0, 3);
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 14)
                        kind = 14;
                  }
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 15)
                        kind = 15;
                  }
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 21)
                        kind = 21;
                  }
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 25)
                        kind = 25;
                  }
                  if (jjCanMove_8(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 31)
                        kind = 31;
                  }
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(27, 33);
                  }
                  if (jjCanMove_10(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 42)
                        kind = 42;
                     jjCheckNAddStates(7, 15);
                  }
                  break;
               case 2:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 8)
                     kind = 8;
                  break;
               case 5:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2) && kind > 9)
                     kind = 9;
                  break;
               case 8:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2) && kind > 10)
                     kind = 10;
                  break;
               case 11:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2) && kind > 11)
                     kind = 11;
                  break;
               case 14:
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2) && kind > 14)
                     kind = 14;
                  break;
               case 17:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2) && kind > 15)
                     kind = 15;
                  break;
               case 18:
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2) && kind > 21)
                     kind = 21;
                  break;
               case 19:
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2) && kind > 25)
                     kind = 25;
                  break;
               case 23:
                  if (jjCanMove_8(hiByte, i1, i2, l1, l2) && kind > 31)
                     kind = 31;
                  break;
               case 57:
                  if (jjCanMove_9(hiByte, i1, i2, l1, l2))
                     jjAddStates(81, 82);
                  break;
               case 101:
                  if (!jjCanMove_10(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 102:
                  if (jjCanMove_10(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(102, 103);
                  break;
               case 105:
                  if (!jjCanMove_10(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 106:
                  if (!jjCanMove_11(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(27, 33);
                  break;
               case 107:
                  if (!jjCanMove_11(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(4, 6);
                  break;
               case 109:
                  if (!jjCanMove_9(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(110);
                  break;
               case 110:
                  if (!jjCanMove_11(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(110);
                  break;
               case 112:
                  if (jjCanMove_9(hiByte, i1, i2, l1, l2))
                     jjAddStates(16, 17);
                  break;
               case 114:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(0, 3);
                  break;
               case 116:
                  if (jjCanMove_9(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 117:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 120:
                  if (jjCanMove_9(hiByte, i1, i2, l1, l2))
                     jjAddStates(18, 19);
                  break;
               case 273:
                  if (!jjCanMove_10(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddStates(7, 15);
                  break;
               case 274:
                  if (!jjCanMove_10(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddTwoStates(274, 275);
                  break;
               case 276:
                  if (!jjCanMove_10(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 277:
                  if (jjCanMove_10(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(277, 278);
                  break;
               case 279:
                  if (jjCanMove_10(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(20, 22);
                  break;
               case 281:
                  if (jjCanMove_10(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(281, 103);
                  break;
               case 282:
                  if (jjCanMove_10(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(282, 283);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 284 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   114, 115, 117, 118, 107, 108, 110, 274, 275, 277, 278, 279, 280, 282, 283, 103, 
   112, 113, 120, 121, 279, 280, 103, 116, 119, 109, 111, 107, 108, 110, 114, 115, 
   117, 118, 219, 224, 227, 232, 235, 240, 244, 250, 254, 260, 264, 270, 272, 179, 
   185, 191, 198, 205, 212, 215, 163, 166, 169, 172, 146, 150, 154, 157, 160, 136, 
   139, 142, 125, 129, 133, 95, 99, 86, 91, 76, 78, 81, 66, 69, 73, 61, 
   62, 57, 58, 104, 105, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec0[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec1[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_3(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec3[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_4(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec4[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_5(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec5[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_6(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec6[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_7(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 255:
         return ((jjbitVec7[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_8(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 3:
         return ((jjbitVec8[i2] & l2) != 0L);
      default : 
         return false;
   }
}
private static final boolean jjCanMove_9(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec11[i2] & l2) != 0L);
      default : 
         if ((jjbitVec9[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_10(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec14[i2] & l2) != 0L);
      case 11:
         return ((jjbitVec15[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec16[i2] & l2) != 0L);
      case 14:
         return ((jjbitVec17[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec18[i2] & l2) != 0L);
      default : 
         if ((jjbitVec12[i1] & l1) != 0L)
            if ((jjbitVec13[i2] & l2) == 0L)
               return false;
            else
            return true;
         return false;
   }
}
private static final boolean jjCanMove_11(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec20[i2] & l2) != 0L);
      case 1:
         return ((jjbitVec21[i2] & l2) != 0L);
      case 2:
         return ((jjbitVec22[i2] & l2) != 0L);
      case 3:
         return ((jjbitVec23[i2] & l2) != 0L);
      case 4:
         return ((jjbitVec24[i2] & l2) != 0L);
      case 5:
         return ((jjbitVec25[i2] & l2) != 0L);
      case 31:
         return ((jjbitVec26[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec27[i2] & l2) != 0L);
      case 51:
         return ((jjbitVec28[i2] & l2) != 0L);
      case 215:
         return ((jjbitVec29[i2] & l2) != 0L);
      case 247:
         return ((jjbitVec30[i2] & l2) != 0L);
      case 250:
         return ((jjbitVec31[i2] & l2) != 0L);
      case 251:
         return ((jjbitVec32[i2] & l2) != 0L);
      case 253:
         return ((jjbitVec33[i2] & l2) != 0L);
      case 254:
         return ((jjbitVec34[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec35[i2] & l2) != 0L);
      default : 
         if ((jjbitVec19[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\73", "\174", "\254", null, null, null, null, 
"\74", "\76", null, null, "\u2225", "\u22a5", "\75", "\53", "\55", null, "\57", 
"\136", "\41", null, "\262", "\263", "\u2074", "\u2075", "\u2076", null, "\u212f", 
"\260", "\u221e", "\162\141\144", "\47", null, null, "\170", "\171", "\130", null, 
null, null, null, null, null, null, "\170\50", "\171\50", null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, "\154\144\50", 
"\154\147\50", null, "\143\142\162\164\50", null, null, null, null, null, null, 
"\162\141\156\144\157\155\50\51", null, null, null, "\72", "\133", "\54", "\135", "\173", "\175", "\51", "\50", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xfffe4fffffffffe1L, 0x7fbfffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[284];
private final int[] jjstateSet = new int[568];
protected char curChar;
public ParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public ParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 284; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
