/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package geogebra.algebra.parser;

public interface ParserConstants {

  int EOF = 0;
  int EOL = 5;
  int CARTESIAN_SPECIAL_SEPERATOR = 6;
  int NOT = 7;
  int OR = 8;
  int AND = 9;
  int EQUAL_BOOLEAN = 10;
  int NOT_EQUAL = 11;
  int LESS = 12;
  int GREATER = 13;
  int LESS_EQUAL = 14;
  int GREATER_EQUAL = 15;
  int PARALLEL = 16;
  int PERPENDICULAR = 17;
  int EQUAL = 18;
  int PLUS = 19;
  int MINUS = 20;
  int MULTIPLY = 21;
  int DIVIDE = 22;
  int POWER = 23;
  int FACTORIAL = 24;
  int UNDEFINED = 25;
  int SQUARED = 26;
  int CUBED = 27;
  int POWER4 = 28;
  int POWER5 = 29;
  int POWER6 = 30;
  int PI = 31;
  int E = 32;
  int DEGREE = 33;
  int RAD = 34;
  int DERIVATIVE = 35;
  int TRUE = 36;
  int FALSE = 37;
  int VARX = 38;
  int VARY = 39;
  int PARAMETRICVAR = 40;
  int FLOAT = 41;
  int EFLOAT = 42;
  int INTEGER = 43;
  int DIGIT = 44;
  int LABEL = 45;
  int INDEX = 46;
  int LETTER = 47;
  int TEXT = 48;
  int CHAR = 49;
  int X_FUNC = 50;
  int Y_FUNC = 51;
  int COS_FUNC = 52;
  int SIN_FUNC = 53;
  int TAN_FUNC = 54;
  int ACOS_FUNC = 55;
  int ASIN_FUNC = 56;
  int ATAN_FUNC = 57;
  int COSH_FUNC = 58;
  int SINH_FUNC = 59;
  int TANH_FUNC = 60;
  int ACOSH_FUNC = 61;
  int ASINH_FUNC = 62;
  int ATANH_FUNC = 63;
  int EXP_FUNC = 64;
  int LOG_FUNC = 65;
  int LD_FUNC = 66;
  int LG_FUNC = 67;
  int SQRT_FUNC = 68;
  int CBRT_FUNC = 69;
  int ABS_FUNC = 70;
  int SGN_FUNC = 71;
  int FLOOR_FUNC = 72;
  int CEIL_FUNC = 73;
  int ROUND_FUNC = 74;
  int GAMMA_FUNC = 75;
  int RANDOM_FUNC = 76;
  int FUNCTION_LABEL = 77;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\"|\"",
    "\"\\u00ac\"",
    "<OR>",
    "<AND>",
    "<EQUAL_BOOLEAN>",
    "<NOT_EQUAL>",
    "\"<\"",
    "\">\"",
    "<LESS_EQUAL>",
    "<GREATER_EQUAL>",
    "\"\\u2225\"",
    "\"\\u22a5\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "<MULTIPLY>",
    "\"/\"",
    "\"^\"",
    "\"!\"",
    "<UNDEFINED>",
    "\"\\u00b2\"",
    "\"\\u00b3\"",
    "\"\\u2074\"",
    "\"\\u2075\"",
    "\"\\u2076\"",
    "<PI>",
    "\"\\u212f\"",
    "\"\\u00b0\"",
    "\"rad\"",
    "\"\\\'\"",
    "<TRUE>",
    "<FALSE>",
    "\"x\"",
    "\"y\"",
    "\"X\"",
    "<FLOAT>",
    "<EFLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LABEL>",
    "<INDEX>",
    "<LETTER>",
    "<TEXT>",
    "<CHAR>",
    "\"x(\"",
    "\"y(\"",
    "<COS_FUNC>",
    "<SIN_FUNC>",
    "<TAN_FUNC>",
    "<ACOS_FUNC>",
    "<ASIN_FUNC>",
    "<ATAN_FUNC>",
    "<COSH_FUNC>",
    "<SINH_FUNC>",
    "<TANH_FUNC>",
    "<ACOSH_FUNC>",
    "<ASINH_FUNC>",
    "<ATANH_FUNC>",
    "<EXP_FUNC>",
    "<LOG_FUNC>",
    "\"ld(\"",
    "\"lg(\"",
    "<SQRT_FUNC>",
    "\"cbrt(\"",
    "<ABS_FUNC>",
    "<SGN_FUNC>",
    "<FLOOR_FUNC>",
    "<CEIL_FUNC>",
    "<ROUND_FUNC>",
    "<GAMMA_FUNC>",
    "\"random()\"",
    "<FUNCTION_LABEL>",
    "\":\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\")\"",
    "\"(\"",
  };

}
