#!/bin/sh

# Creates a general Linux version of GeoGebra.
# Requires python3.
# The result .tar.gz will be put into ../../../../build/.

# @author Zoltan Kovacs <zoltan@geogebra.org>

VERSION_STRING=`cat ../../../../build/unpacked/version.txt`
if [ "$VERSION_STRING" = "" ]; then
 echo "Please build GeoGebra first."
 exit 1
 fi

. ../../autobuild.conf

if [ "$PYTHON3" = "" ]; then
 PYTHON3=`which python3 2>&1 >/dev/null`
 if [ "$PYTHON3" = "" ]; then
  echo Python3 is required to run this script.
  exit 1
  fi
 fi

# Packaging hicolor icons:
cd ../../../../icons
tar czf $SVNDIR/geogebra/scripts/autobuild/linux/generic/hicolor.tgz hicolor
cd $SVNDIR/geogebra/scripts/autobuild/linux/generic

$PYTHON3 ./create_geogebra_linux.py \
 $VERSION_STRING \
 ../../../../build/unpacked \
 ../../../../build/unsigned \
 geogebra \
 ../../../../_LICENSE.txt \
 geogebra.xml \
 geogebra.desktop \
 hicolor.tgz \
 ../../../../build
