#!/bin/bash
#---------------------------------------------
# Script to start GeoGebra
#---------------------------------------------

#---------------------------------------------
# Used environment variables:
#
# GG_SCRIPTNAME=<name of originally called script to start GeoGebra> # If unset, name of this script will be used
#
# GG_PATH=<path of directory containing geogebra.jar> # If unset, path of this script will be used.
# In this case if the path of script does not contain the geogebra.jar file, /usr/share/geogebra will be used.
#
# JAVACMD=<Java command> # If unset, java will be used

#---------------------------------------------
# If GG_SCRIPTNAME not set, use name of this script

if [ -z "$GG_SCRIPTNAME" ]; then
	GG_SCRIPTNAME=$(basename $0)
fi

#---------------------------------------------
# Define usage function

func_usage()
{
cat << _USAGE
Usage: $GG_SCRIPTNAME [Java-options] [GeoGebra-options] [FILE]

GeoGebra - Dynamic mathematics software

Java options:
  -Xms<size>                        Set initial Java heap size
  -Xmx<size>                        Set maximum Java heap size

GeoGebra options:
  --help                            Show this help message
  --v                               Show version information
  --language=<iso_code>             Set language using locale code, e.g. en, de_AT
  --showAlgebraInput=<boolean>      Show/hide algebra input field
  --showAlgebraInputTop=<boolean>   Show algebra input field at top/bottom
  --showAlgebraWindow=<boolean>     Show/hide algebra window
  --showSpreadsheet=<boolean>       Show/hide spreadsheet
  --showCAS=<boolean>               Show/hide CAS window
  --showSplash=<boolean>            Enable/disable the splash screen
  --enableUndo=<boolean>            Enable/disable Undo
  --fontSize=<number>               Set default font size
  --showAxes=<boolean>              Show/hide coordinate axes
  --settingsFile=<path>|<filename>  Load/save settings from/in a local file
  --resetSettings                   Reset current settings
  --CAS=[MPREDUCE|MAXIMA|MATHPIPER] Select which CAS to use, default MPREDUCE
  --maximaPath=<path>               Specify where Maxima is installed and select Maxima as current CAS
  --antiAliasing=<boolean>          Turn anti-aliasing on/off
  --regressionFile=<filename>       Export textual representations of dependent objects, then exit
_USAGE
}

#---------------------------------------------
# If JAVACMD not set, use java

if [ -z "$JAVACMD" ]; then
	JAVACMD='java'
fi

#---------------------------------------------
# Check for option --help and pass memory options to Java, others to GeoGebra

for i in "$@"; do
	case "$i" in
	--help | --hel | --he | --h )
		func_usage; exit 0 ;;
	esac
	if [ $(expr match "$i" '.*-Xm') -ne 0 ]; then
		if [ -z "$JAVA_OPTS" ]; then
			JAVA_OPTS="$i"
		else
			JAVA_OPTS="$JAVA_OPTS $i"
		fi
		shift $((1))
	else
		if [ $(expr match "$i" '.*--') -ne 0 ]; then
			if [ -z "$GG_OPTS" ]; then
				GG_OPTS="$i"
			else
				GG_OPTS="$GG_OPTS $i"
			fi
			shift $((1))
		fi
	fi
done

#---------------------------------------------
# If memory not set, change to GeoGebra defaults

if [ $(expr match "$JAVA_OPTS" '.*-Xmx') -eq 0 ]; then
	JAVA_OPTS="$JAVA_OPTS -Xmx512m"
fi
if [ $(expr match "$JAVA_OPTS" '.*-Xms') -eq 0 ]; then
	JAVA_OPTS="$JAVA_OPTS -Xms32m"
fi

#---------------------------------------------
# If GG_PATH not set, use path of this script

if [ -z "$GG_PATH" ]; then
	GG_PATH="${BASH_SOURCE[0]}"
	if [ -h "${GG_PATH}" ]; then
		while [ -h "${GG_PATH}" ]; do
		GG_PATH=`readlink "${GG_PATH}"`
		done
	fi
	pushd . > /dev/null
	cd `dirname ${GG_PATH}` > /dev/null
	GG_PATH=`pwd`
	popd > /dev/null
	
	test -r "${GG_PATH}/geogebra.jar" || GG_PATH=/usr/share/geogebra
fi

#---------------------------------------------
# Run

exec "$JAVACMD" $JAVA_OPTS -jar "$GG_PATH/geogebra.jar" $GG_OPTS "$@"
